### ISSUE TITLE
Invalid format string when using pause.until()

### ISSUE THREAD

**Issue by romanrdgz** [jgillick/python-pause#6]
Observed with Python 3.5.2 under windows:

import pause
import datetime

today = datetime.datetime.now()
tomorrow = today.replace(hour=0, minute=0, second=0, microsecond=0) + datetime.timedelta(days=1)
print(tomorrow, type(tomorrow))
pause.until(tomorrow)  # Will wait until 00:00

This results in the following output:
2017-10-06 00:00:00 <class 'datetime.datetime'>
Traceback (most recent call last):
  File "test.py", line 137, in <module>
    pause.until(tomorrow)  # Will wait until 00:00
  File "c:\Users\myuser\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pause\__init__.py", line 46, in until
    end = float(time.strftime('%s.%f'))
ValueError: Invalid format string

**Comment by SmartManoj** [comment]
`pip install --upgrade git+git://github.com/jgillick/python-pause`
